version: '3.9'

networks:
  net:
    driver: bridge

services:
  app:
    build:
      context: ./src/chainlit  # Directory containing Dockerfile for chainlit app
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - LISTEN_PORT=8000
    ports:
      - "8001:8000"  # Maps port 8000 of the container to port 8001 of the host
    networks:
      - net

  server:
    build:
      context: ./src/chroma-db/  # Directory containing Dockerfile for chroma server
      dockerfile: Dockerfile
    volumes:
      - ./src/chroma-db:/chroma
      - ./src/chroma-db/index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config /chroma/log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8000:8000"
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
